FROM centos/httpd-24-centos7:latest

MAINTAINER green@moxielogic.org

RUN mkdir -p /opt/rh/http24/root/var/www/html
ADD MoxieLogic /opt/rh/http24/root/var/www/html/MoxieLogic
ADD index.html /opt/rh/http24/root/var/www/html/index.html

