FROM centos/httpd-24-centos7:latest

MAINTAINER green@moxielogic.org

ADD MoxieLogic /var/www/html/MoxieLogic
ADD index.html /var/www/html/index.html
RUN curl -o /etc/pki/tls/certs/localhost.crt https://acme-v02.api.letsencrypt.org/acme/cert/03ec6d253e1afef1b41e2932db0b65dfb3d5
